language: node_js
node_js:
- node
install:
- cd $TRAVIS_BUILD_DIR/client && npm install && npm run typings
- cd $TRAVIS_BUILD_DIR/server && npm install && npm run typings
- npm install -g vsce
script:
- cd $TRAVIS_BUILD_DIR/client && npm run lint
- cd $TRAVIS_BUILD_DIR/server && npm run compile
- cd $TRAVIS_BUILD_DIR/client && vsce package
after_success:
- test -n $TRAVIS_TAG && test $TRAVIS_BRANCH='master' && cd $TRAVIS_BUILD_DIR/client && vsce publish -p $VSCODE_TOKEN
env:
  global:
    secure: R887iYkNIDn/k0S//0r85BErKe9awlFpBE9F4/42kpXTNMbj/B4+VUOA78xLu3s/HA0LL9LBsDa2Nv3cuxKqKyXERM6XM+9fMt81r+nAZuh+S4f4dN3MQZx08MZh66v02Js8R8B0vAqQuqC3h9GC4Zb+GbHBwo1eGerEzhd46Ob19mkxrbBJu3LsU410sIfh8kDi4vZc6SHJBU/LotYR6R4wJlUNQsFjwPUvqJ4KCkLb5E3JBsjDjDIetB5M9LP516CcmwLT2AfI2Rd03p+xsHPwVtkOQ88JPJbbQnmsUbyHDRM4k8BRgBM1W+qDqwsdR+kd1JS6ZwafTonRQTnhhNuuNmYJfqx9RMnh6bMai40EJaOOYSgoHNq9jBhT0rfLbH08H2A1my86LVQEtNGNfgKvCkJXRJgJUWv7z7FpKxK9+C5GRYWka6OI3uB7huJXPtrCDw9YVPUEI261OYrLq3PW86DWyHU1s34t+a2Kqh1N2oY0+SApVPVp9FfHNg6axRs2eQscIt+ILHy9I1FQ2v15ChrS+fwTwWgu8WVYAUfxZuQgHH8FeTD6aQGZTPD9Popr44711rLXJ9IE3IbP+guOzgvInzvmliHu4OkFKVaWq9+VTLZc347COoFueL4Gvl3kA48QI2D7Bq73qeQC8xZqJeE4yHlyUKFak97Etlc=
